name: tinycolor
description: Flutter Color manipulation and conversion, ported from JS tinycolor2
version: 1.0.3
author: Foo() <developer@foostudio.mx>
homepage: https://github.com/FooStudio/tinycolor

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=0.1.4 <3.0.0"

dependencies:
  pigment: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
